
const mongoose = require("mongoose");
const Job  = require("../models/Job.model.js")

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost/tech-job-board";

mongoose
  .connect(MONGO_URI)
  .then((x) => {
    console.log(`Connected to Mongo! Database name: "${x.connections[0].name}"`);
  })
  .catch((err) => {
    console.error("Error connecting to mongo: ", err);
  });

  const data = [
    {
      jobTitle:'Executive Director',
      company: 'Amesbury Housing Authority',
      location: 'Amesbury, MA',
      salary: '75,000',
      workHours: 'Full-Time',
      description: "The Amesbury Housing Authority seeks an experienced housing administrator for leadership and management of its programs, properties, and contracts. The Amesbury Housing Authority owns, operates and manages 371 units, 205 units of state-aided elderly/handicapped public housing, 27 units chapter 200, 13 units of state-aided ch-705 family housing, 8 units chapter 689, 84 HCV, 10 section 8 new construction, and 24 PBV. Amesbury Housing Authority is also the management agent for the Merrimac Housing Authority which owns 48 units of state aided elderly/disabled public housing and 4 units of state aided chapter 705 family housing.The Amesbury Housing Authority seeks an experienced housing administrator for leadership and management of its programs, properties, and contracts. The Amesbury Housing Authority owns, operates and manages 371 units, 205 units of state-aided elderly/handicapped public housing, 27 units chapter 200, 13 units of state-aided ch-705 family housing, 8 units chapter 689, 84 HCV, 10 section 8 new construction, and 24 PBV. Amesbury Housing Authority is also the management agent for the Merrimac Housing Authority which owns 48 units of state aided elderly/disabled public housing and 4 units of state aided chapter 705 family housingThe Amesbury Housing Authority seeks an experienced housing administrator for leadership and management of its programs, properties, and contracts. The Amesbury Housing Authority owns, operates and manages 371 units, 205 units of state-aided elderly/handicapped public housing, 27 units chapter 200, 13 units of state-aided ch-705 family housing, 8 units chapter 689, 84 HCV, 10 section 8 new construction, and 24 PBV. Amesbury Housing Authority is also the management agent for the Merrimac Housing Authority which owns 48 units of state aided elderly/disabled public housing and 4 units of state aided chapter 705 family housingThe Amesbury Housing Authority seeks an experienced housing administrator for leadership and management of its programs, properties, and contracts. The Amesbury Housing Authority owns, operates and manages 371 units, 205 units of state-aided elderly/handicapped public housing, 27 units chapter 200, 13 units of state-aided ch-705 family housing, 8 units chapter 689, 84 HCV, 10 section 8 new construction, and 24 PBV. Amesbury Housing Authority is also the management agent for the Merrimac Housing Authority which owns 48 units of state aided elderly/disabled public housing and 4 units of state aided chapter 705 family housing "
    
    },
    {
      jobTitle:'Executive Assistant',
      company: 'GEoVera Holdings',
      location: 'Fairfield, CA',
      salary: '50,000',
      workHours:'Part-Time',
      description: "The Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilities.The Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilitiesThe Executive Assistant supports executive management by leading and coordinating corporate business initiatives and performs a variety of administrative and project management responsibilities "
    
    },

    {
      jobTitle:'Plumber',
      company: 'Twin Belle Plumbing-Heating -A/C',
      location: 'Katonah,NY',
      salary:'45,000',
      workHours: 'Full-Time',
      description: "Technicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repair.Technicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repairTechnicians: We are seeking to employ experienced residential air conditioning and gas heating technicians. We also do PLUMBING service and repair experience is a plus but we will train. Applicants must have a minimum of 3 years experience in HVAC service and repair"
    
    },
    {
      jobTitle:'Home Health Physical Therapist',
      company: 'Aveanna Healthcare',
      location: 'Englewood, Fl',
      salary:'72,000',
      description: "We are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-being.We are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-beingWe are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-beingWe are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-beingWe are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-beingWe are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-beingWe are looking for a Physical Therapist (PT) to join our team! You will utilize your clinical expertise to assess, teach, and deliver therapy interventions and treatment directed by the Physician as established in the home health plan of care. You will collaborate with interdisciplinary team members, receiving and providing pertinent updates to optimize patient well-being. "
    
    },
    
    {

      jobTitle:'Reporter',
      company: 'Newsmax Media',
      location: 'Washingtion, DC',
      salary: '65,000',
      workHours:'Full-Time',
      description: "The successful candidate will be a proven on-air reporter, in possession of a reel showcasing attention-grabbing talent, engagement and intelligence.Will have an excellent already-developed contact list, including many who’s  leaders in Congress, and related government agencies. Will have outstanding writing and production skills and will be required to deliver high quality news stories.  Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements.Must be able to work with camera and technical crews, as well as possess excellent people skills and be able to react swiftly and effectively to story and production requirements "
    },
    
 {
    jobTitle:'Web Developer',
    company: 'Adecco',
    location: 'PittsField, NH',
    salary: '60,000',
    workHours: 'Part-Time',
    description: "Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes. "
 },
 {
    jobTitle:'Web Developer',
    company: 'SPECTRUM',
    location: 'Coppell, TX',
    salary: '70,000',
    workHours: 'Part-Time',
    description: "Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements."
 },

 {
    jobTitle:'Jr. Net Web Developer',
    company: 'QT9 Software',
    location: 'Aurora, IL',
    salary: '50,000',
    workHours: 'Full-Time',
    description: "QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges."
 },
 {
    jobTitle:'Full Stack Web Developer',
    company: 'delaware county community college',
    location: 'Media, PA',
    salary: '90,000',
    workHours: 'Full-Time',
    description: "The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app "
 },

 {
  jobTitle:'Full Stack Web Developer',
  company: 'media Query',
  location: 'Miami, FL',
  salary: '90,000',
  workHours: 'Full-Time',
  description: "The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.vThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app. "
},

  ]
  
  Job.create(data)
  .then( (jobsFromDB) => {
    console.log(`Added ${jobsFromDB.length} jobs to the DB: `, jobsFromDB);
    mongoose.connection.close();
  })
  .catch( (error) => {
    console.log('Error while inserting jobs to the DB: ', error);
  });

