
const mongoose = require("mongoose");
const Job  = require("../models/Job.model.js")

const MONGO_URI = process.env.MONGODB_URI || "mongodb://localhost/tech-job-board";

mongoose
  .connect(MONGO_URI)
  .then((x) => {
    console.log(`Connected to Mongo! Database name: "${x.connections[0].name}"`);
  })
  .catch((err) => {
    console.error("Error connecting to mongo: ", err);
  });

  const data = [
    
 {
    jobTitle:'Web Developer',
    company: 'Adecco',
    location: 'PittsField, NH',
    salary: '60,000',
    workHours: 'Part-Time',
    description: "Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes.Adecco is assisting our client, MSA Globe, a global designer, manufacturer, and distributor of safety devices and equipment, in staffing a temporary Web Developer position at their Pittsfield, NH location. This is a 4+ month contract assignment. This position can support remote, hybrid or on-site; however, candidate must be available for a minimum of two on-site visits for training/setup purposes. "
 },
 {
    jobTitle:'Web Developer',
    company: 'SPECTRUM',
    location: 'Coppell, TX',
    salary: '70,000',
    workHours: 'Part-Time',
    description: "Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements.Design, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirementsDesign, develop, modify, and implement applications and/or services designed to support organizations applications. This position will code and perform unit and integration testing of software to ensure proper and efficient execution and adherence to business and technical requirements."
 },

 {
    jobTitle:'Jr. Net Web Developer',
    company: 'QT9 Software',
    location: 'Aurora, IL',
    salary: '50,000',
    workHours: 'Full-Time',
    description: "QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges.QT9 Software is seeking a self-motivated and quick learning Jr. Net Web Developer to join our Development Team. As a Jr.Net Web Developer, you will actively be developing core software in both the web and WinForms. It is expected to not only develop code but come up with new effective ways to solve interface and process challenges."
 },
 {
    jobTitle:'Full Stack Web Developer',
    company: 'delaware county community college',
    location: 'Media, PA',
    salary: '90,000',
    workHours: 'Full-Time',
    description: "The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile appThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app "
 },

 {
  jobTitle:'Full Stack Web Developer',
  company: 'media Query',
  location: 'Miami, FL',
  salary: '90,000',
  workHours: 'Full-Time',
  description: "The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.vThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app. "
},
{
  jobTitle:'Software Engineer',
  company: 'The Panther Group',
  location: 'Orlando, FL',
  salary: '100,000',
  workHours: 'Full-Time',
  description: "The Panther Group is looking for motivated workers to join the team as a Software Engineer working for a local Government Contractor.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.vThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which pow"
},
{
  jobTitle:'Founding Software Engineer - Backend',
  company: 'Jobot',
  location: 'San Francisco, CA',
  salary: '250,000',
  workHours: 'Full-Time',
  description: "We are a team of repeat founders who believe commercial real-estate ownership and investment should be accessible, frictionless, and transparent for everyone.We are looking for a Founding Software Engineer to join our three co-founders in this early stage venture. The Founding Engineer will be focused on 100% greenfield development. web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.vThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which pow"
},
{
  jobTitle:'Software Engineer (Back end)',
  company: 'Randstad USA',
  location: 'Chicago, IL',
  salary: '130,000',
  workHours: 'Full-Time',
  description: "Our client's location in Chicago, IL, currently has an opportunity for a Software Engineer to produce scalable software solutions. You'll be part of a cross-functional team responsible for the entire software development life cycle, from conception to deployment.We are looking for a Founding Software Engineer to join our three co-founders in this early stage venture. The Founding Engineer will be focused on 100% greenfield development. web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.The Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which powers the Colleges public website, web portal and Customer Service wiki as well as administer and support the College SaaS mobile app.vThe Full Stack Web Developer in collaboration with the Web Team will develop, maintain, and provide support for the Colleges Drupal content management system which pow"
}

  ];
  
  Job.create(data)
  .then( (jobsFromDB) => {
    console.log(`Added ${jobsFromDB.length} jobs to the DB: `, jobsFromDB);
    mongoose.connection.close();
  })
  .catch( (error) => {
    console.log('Error while inserting jobs to the DB: ', error);
  });

